# YAML pipeline definition
# Triggered when changes are pushed to the repository

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Your Azure Subscription'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Your Resource Group Name'
    location: 'Your Azure Region'
    templateLocation: 'Linked artifact'
    csmFile: 'Your ARM Template for the Linux Virtual Machine (LinuxVM.json)'
    csmParametersFile: 'Your ARM Template Parameters for the Linux Virtual Machine (LinuxVM.parameters.json)'
    deploymentMode: 'Incremental'

